// Copyright and related rights waived via CC0.
//
// obi_tlul_bridge
// ----------------
// Drives an OpenTitan TileLink-UL device (here: spi_host) from Croc's native
// OBI bus. Croc's fabric is OBI end-to-end; spi_host speaks TL-UL. This is
// the one point-to-point translation between the two, acting as the TL-UL
// *host* (channel A: request, channel D: response) towards spi_host's
// device port.
//
// Single-outstanding by design: a new OBI request is only granted once the
// previous TL-UL transaction has completed (state_q back in S_IDLE). Croc's
// SbrObiCfg has UseRReady=1'b0 (the OBI response side has no backpressure --
// once rvalid is asserted the master must accept it), so there is nothing to
// arbitrate on the response side either; a combinational gnt (CombGnt is
// permitted, not required, by SbrObiCfg) keeps this simple. spi_host is a
// register-mapped, firmware-paced peripheral -- nothing here needs the
// pipelining a faster subordinate might justify.
//
// TL-UL command-integrity note: spi_host_reg_top instantiates
// tlul_cmd_intg_chk unconditionally on its tl_i port. It recomputes a SECDED
// syndrome over {a_valid's associated fields} and raises reg_error on any
// mismatch -- if we drove a_user.cmd_intg as '0 (or anything not matching
// tlul_pkg's own encoding), *every* transaction would come back as a TL-UL
// error. So this bridge builds the channel-A struct in two steps: assemble
// every field except cmd_intg, then call tlul_pkg::get_cmd_intg() on that
// struct to compute the one field that has to be correct. Response-side
// integrity (d_user.rsp_intg, generated by spi_host for us) is not checked
// here -- nothing on the device side requires the host to verify it, so
// skipping it doesn't break functionality, only the optional extra hardening.

`include "obi/typedef.svh"

module obi_tlul_bridge import tlul_pkg::*; #(
  parameter obi_pkg::obi_cfg_t ObiCfg    = obi_pkg::ObiDefaultConfig,
  parameter type               obi_req_t = logic,
  parameter type               obi_rsp_t = logic
) (
  input  logic clk_i,
  input  logic rst_ni,

  // OBI subordinate port (from Croc's crossbar / UserDesign demux)
  input  obi_req_t obi_req_i,
  output obi_rsp_t obi_rsp_o,

  // TL-UL host port (to spi_host's tl_i/tl_o)
  output tl_h2d_t tl_h2d_o,
  input  tl_d2h_t tl_d2h_i
);

  typedef enum logic {
    S_IDLE,
    S_WAIT_RSP
  } state_e;

  state_e state_q, state_d;

  logic req_fire;
  assign req_fire = tl_h2d_o.a_valid && tl_d2h_i.a_ready;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) state_q <= S_IDLE;
    else         state_q <= state_d;
  end

  always_comb begin
    state_d = state_q;
    unique case (state_q)
      S_IDLE:     if (req_fire)        state_d = S_WAIT_RSP;
      S_WAIT_RSP: if (tl_d2h_i.d_valid) state_d = S_IDLE;
      default:    state_d = S_IDLE;
    endcase
  end

  // ---------------------------------------------------------------------
  // Channel A (request)
  // ---------------------------------------------------------------------
  tl_a_op_e a_opcode;
  assign a_opcode = obi_req_i.a.we ? PutFullData : Get;

  // Every field except a_user.cmd_intg -- get_cmd_intg() below needs the
  // fully-assembled-minus-cmd_intg struct to compute the correct code.
  tl_h2d_t tl_h2d_pre_intg;
  always_comb begin
    tl_h2d_pre_intg           = TL_H2D_DEFAULT;
    tl_h2d_pre_intg.a_valid   = obi_req_i.req && (state_q == S_IDLE);
    tl_h2d_pre_intg.a_opcode  = a_opcode;
    tl_h2d_pre_intg.a_param   = '0;
    tl_h2d_pre_intg.a_size    = top_pkg::TL_SZW'(2'd2); // fixed 4-byte word, matches Croc's DataWidth=32
    tl_h2d_pre_intg.a_source  = top_pkg::TL_AIW'(obi_req_i.a.aid);
    tl_h2d_pre_intg.a_address = obi_req_i.a.addr;
    tl_h2d_pre_intg.a_mask    = obi_req_i.a.be;
    tl_h2d_pre_intg.a_data    = obi_req_i.a.wdata;
    tl_h2d_pre_intg.a_user    = TL_A_USER_DEFAULT; // tl_type: DataType -- this is a register access, not an instruction fetch
    tl_h2d_pre_intg.d_ready   = 1'b1;              // OBI's UseRReady=0: we must always be able to accept the response
  end

  always_comb begin
    tl_h2d_o                 = tl_h2d_pre_intg;
    tl_h2d_o.a_user.cmd_intg = get_cmd_intg(tl_h2d_pre_intg);
  end

  // ---------------------------------------------------------------------
  // Channel D (response)
  // ---------------------------------------------------------------------
  always_comb begin
    obi_rsp_o        = '0;
    obi_rsp_o.gnt     = req_fire;
    obi_rsp_o.rvalid  = (state_q == S_WAIT_RSP) && tl_d2h_i.d_valid;
    obi_rsp_o.r.rdata = tl_d2h_i.d_data;
    obi_rsp_o.r.rid   = ObiCfg.IdWidth'(tl_d2h_i.d_source); // spi_host echoes a_source back unchanged, per TL-UL
    obi_rsp_o.r.err   = tl_d2h_i.d_error;
  end

endmodule
